# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-30 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100, null=True, verbose_name='日期')),
                ('day_amt', models.CharField(max_length=100000000, null=True, verbose_name='一天销售额')),
                ('month_amt', models.CharField(max_length=100000000, null=True, verbose_name='一月销售额')),
            ],
        ),
    ]
