# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-17 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echarts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ip',
            old_name='ip',
            new_name='ipaddr',
        ),
        migrations.RenameField(
            model_name='ip',
            old_name='region',
            new_name='lonandlatandcity',
        ),
    ]
