# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-17 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echarts', '0002_auto_20171017_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='lonandlatandcity',
        ),
        migrations.AddField(
            model_name='ip',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='ip',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='ip',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='ip',
            name='ipaddr',
            field=models.CharField(max_length=100, null=True, verbose_name='ip地址'),
        ),
    ]
