# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cartafter',
            fields=[
                ('count', models.IntegerField(verbose_name='计数')),
                ('itemid', models.IntegerField(primary_key=True, serialize=False, verbose_name='商品')),
                ('property', models.CharField(max_length=50, verbose_name='属性')),
            ],
            options={
                'db_table': 'cartafter',
            },
        ),
        migrations.CreateModel(
            name='transafter',
            fields=[
                ('count', models.IntegerField(verbose_name='计数')),
                ('itemid', models.IntegerField(primary_key=True, serialize=False, verbose_name='商品')),
                ('property', models.CharField(max_length=50, verbose_name='属性')),
            ],
            options={
                'db_table': 'transafter',
            },
        ),
        migrations.CreateModel(
            name='viewafter',
            fields=[
                ('count', models.IntegerField(verbose_name='计数')),
                ('itemid', models.IntegerField(primary_key=True, serialize=False, verbose_name='商品')),
                ('property', models.CharField(max_length=50, verbose_name='属性')),
            ],
            options={
                'db_table': 'viewafter',
            },
        ),
    ]
