# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-13 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名字')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('sum', models.IntegerField(verbose_name='总和')),
                ('price', models.CharField(max_length=100, verbose_name='价格')),
            ],
            options={
                'db_table': 'result',
            },
        ),
    ]
