# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-13 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echarts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
