# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-13 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echarts', '0002_auto_20170913_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='sum',
            new_name='mysum',
        ),
    ]
